CREATE TABLE bookmarks_data (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating INTEGER NOT NULL CONSTRAINT rating_range CHECK (rating > 0 AND rating < 6)
);